### ISSUE TITLE
Picom config 

### ISSUE THREAD

**Issue by RanceH** [EndeavourOS-Community-Editions/openbox#5]
The picom config in the openbox repo is apparently old with a deprecated setting.  With the picom config file from this repo in place picom won't start.  Picom starts fine when the conf file is moved out of the way.

I will try to get some debugging output from a xephyr session and post it.

**Comment by flyingcakes85** [comment]
For the time being, I think we should not autostart picom altogether? Because same config doesn't for many people. Users need to slightly modify or enable/disable features to make it work.
How do you think about it?

**Comment by killajoe** [comment]
> On an unrelated note, the wiki article on the EOS website that discusses window managers has a link to the qtile repo here, but no mention of the openbox setup

could you link to this?

**Comment by RanceH** [comment]
> could you link to this?

I don' see why that wouldn't work, but Qtile gets its own writeup and a link to the github qtile repo.  I found **this one** by exploring what else the community might offer.  Probably need to add a page to the EOS website for Openbox and then in that link to this repo.

**Comment by flyingcakes85** [comment]
@RanceH Joe meant that could you please share a weblink to the article you mentioned.

Thanks

**Comment by RanceH** [comment]
So sorry for the misunderstanding and the delay.  Ive been out of pocket for a few days.

The category article on the EOS web site is here: [Window Managers](https://discovery.endeavouros.com/category/window-tiling-managers/)

The the qtile article is linked from this one.

Its my suggestion that this page get updated to include an openbox article a la sway, qtile, etc.

**Comment by flyingcakes85** [comment]
Seems like yes, Openbox was inadvertently left out.

@killajoe

**Comment by flyingcakes85** [comment]
<closed mistakenly, pressed the wrong button; reopened the issue>

**Comment by flyingcakes85** [comment]
https://discovery.endeavouros.com/window-tiling-managers/openbox/2022/03/

**Comment by killajoe** [comment]
default picom now autostarts itself from xdg implementation in addition so if something like dex is used it will start without using exec commands in configs. 

in general it is a better approach to not set any picom.conf per default and leave it empty with a comment for the user to enable and setup.
